# Generated by Django 5.2.6 on 2025-09-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_name', models.CharField(max_length=45)),
                ('password', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=75)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
