# Generated by Django 5.2.6 on 2025-09-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_admin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
