# Generated by Django 5.2.6 on 2025-09-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
