# Generated by Django 5.2.6 on 2025-09-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_rename_first_name_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_lot',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Rental_spot',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=4)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.rental_lot')),
            ],
        ),
    ]
