# Generated by Django 5.2.6 on 2025-09-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_registerd_spot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registerd_spot',
            new_name='Registered_spot',
        ),
    ]
