# Generated by Django 5.2.6 on 2025-09-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_rename_registerd_spot_registered_spot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registered_spot',
        ),
    ]
