# Generated by Django 5.2.6 on 2025-09-16 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_delete_registered_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_spot',
            fields=[
                ('registered_id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaving_time', models.DateTimeField(null=True)),
                ('phone_number', models.IntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.rental_lot')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.rental_spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.user')),
            ],
        ),
    ]
