# Generated by Django 5.2.6 on 2025-10-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_registered_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=75),
        ),
    ]
