# Generated by Django 5.2.6 on 2025-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_alter_admin_password_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
